# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  flake.nixosModules.framework13ProHardware =
    {
      config,
      lib,
      modulesPath,
      ...
    }:
    {
      # To be generated
    };
}
