#!/bin/bash +e

# This needs to be in the home folder and needs
# to be chmod +x so it runs right.

linux_get_bat ()
{
    bf=$(cat $BAT_FULL)
    bn=$(cat $BAT_NOW)
    BAT=`echo "100 * $bn / $bf" | bc`
    echo $BAT
}

freebsd_get_bat ()
{
    echo "$(sysctl -n hw.acpi.battery.life)%"

}

system=$(uname -s)

if [ "$1" = "test" ]; then
    # Currently, it assumes that if it is a mac it has a battery (it will do, I don't like iMacs)
    if [[ -L /sys/class/power_supply/BAT0 || "$system" = "Darwin" ]]; then
        exit 0
    fi
    exit 1
fi

case $system in
    "Linux")
        if [ -L /sys/class/power_supply/BAT0 ]; then
            BATPATH=/sys/class/power_supply/BAT0
            STATUS=$BATPATH/status
            BAT_FULL=$BATPATH/energy_full
            BAT_NOW=$BATPATH/energy_now
            if [ "$1" = `cat $STATUS` -o "$1" = "" ]; then
                echo $(linux_get_bat)%
            fi
        fi
        ;;
    "FreeBSD")
        STATUS=`sysctl -n hw.acpi.battery.state`
        case $1 in
            "Discharging")
                if [ $STATUS -eq 1 ]; then
                    freebsd_get_bat
                fi
                ;;
            "Charging")
                if [ $STATUS -eq 2 ]; then
                    freebsd_get_bat
                fi
                ;;
            "")
                freebsd_get_bat
                ;;
        esac
        ;;
    "Darwin")
        case $1 in
            "Discharging")
                ext="No";;
            "Charging")
                ext="Yes";;
        esac

        ioreg -c AppleSmartBattery -w0 | \
            grep -o '"[^"]*" = [^ ]*' | \
            sed -e 's/= //g' -e 's/"//g' | \
            sort | \
            while read key value; do
                case $key in
                    "MaxCapacity")
                        export maxcap=$value;;
                    "CurrentCapacity")
                        export curcap=$value;;
                    "FullyCharged")
                        if [ "$value" = "Yes" ]; then
                            exit
                        fi
                        ;;
                esac
                if [[ -n "$maxcap" && -n $curcap ]]; then
                    BAT=`echo "100 * $curcap / $maxcap" | bc`
                    echo ${BAT}%
                    exit
                fi
            done
    esac
