require("tap.plugins.completion-nvim")
require("tap.plugins.fugitive")
require("tap.plugins.gitsigns")
require("tap.plugins.lualine")
require("tap.plugins.telescope")
require("tap.plugins.treesitter")
require("tap.plugins.winresizer")
