# ============================== Loading ==============================
# Loads different file for each environment, also setting variables
if [ -f ~/.zshrc_work ]; then
    echo 'At work...'
    DEFAULT_USER="payneth"
    export LOCATION='work'
    source ~/.zshrc_work
fi

if [ -f ~/.zshrc_home ]; then
    echo 'At home...'
    USER=`whoami`
    if [ $USER = 'tapayne88' ] ||
       [ $USER = 'tapayne' ] ||
       [ $USER = 'tpayne' ]; then
        DEFAULT_USER=$USER
    fi
    export LOCATION='home'
    source ~/.zshrc_home
fi

# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
# ZSH_THEME="tpayne-simple"
# DEFAULT_USER="tapayne88"

# Disables scroll lock shortcut (Ctrl+s)
stty -ixon

# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Comment this out to disable bi-weekly auto-update checks
# DISABLE_AUTO_UPDATE="true"

# Uncomment to change how many often would you like to wait before auto-updates occur? (in days)
# export UPDATE_ZSH_DAYS=13

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
# COMPLETION_WAITING_DOTS="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(git command-not-found tpayne-vi-mode)

# Add environment config first
source $HOME/.config/zsh/environment.zsh

if [ -n "$SSH_CLIENT" ] || [ -n "$SSH_TTY" ]; then
    ZSH_THEME="tpayne-simple"
else
    ZSH_THEME="tpayne"

    # Start tmux at start of each session (only when local)
    if [[ $TERM != "screen" && -z "$TMUX" ]]; then
        tmux > /dev/null 2>&1
    fi
fi

# Add zsh and aliases (order is important - don't know why)
source $ZSH/oh-my-zsh.sh
source $HOME/.config/zsh/aliases.zsh
KEYTIMEOUT=1
