add_newline = true

# Which is equivalent to
format = """
$username\
$hostname\
$shlvl\
$singularity\
$kubernetes\
$directory\
$vcsh\
$git_branch\
${custom.git_worktree} \
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
$fill\
$docker_context\
$package\
$cmake\
$cobol\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$golang\
$helm\
$java\
$julia\
$kotlin\
$lua\
$nim\
$nodejs\
$ocaml\
$perl\
$php\
$pulumi\
$purescript\
$python\
$rlang\
$red\
$ruby\
$rust\
$scala\
$swift\
$terraform\
$vlang\
$vagrant\
$zig\
$nix_shell\
$conda\
$memory_usage\
$aws\
$gcloud\
$openstack\
$env_var\
$crystal\
$custom\
$line_break\
$jobs\
$battery\
$time\
$status\
$shell\
$character"""

right_format = """$cmd_duration"""

[fill]
symbol = " "

[character]
success_symbol = "[❯](white)"

[directory]
format = "[$path]($style)[$read_only]($read_only_style)"
style = "yellow"
read_only = " "

[git_branch]
format = " on [$symbol$branch]($style)"
symbol = " "
style = "green"

[git_status]
format = "[$all_status$ahead_behind]($style) "
up_to_date = "•"
conflicted = ""
stashed = ""
modified = "⋯"
deleted = ""
style = "white"

[custom.git_worktree]
command = "basename $(git rev-parse --show-toplevel)"
when = """ test $(git worktree list | wc -l) -gt 1 """
format = "[\\($output\\)]($style)"
style = "bright-black"

[git_commit]
tag_symbol = " "

[lua]
format = "[$symbol($version )]($style)"
symbol = " "

[nodejs]
format = "[$symbol($version )]($style)"
style = "purple"

[php]
format = "[$symbol($version )]($style)"
symbol = " "

[cmd_duration]
min_time = 0
format = "[$duration]($style)"
style = "bold italic cyan"
