add_newline = true

right_format = """$cmd_duration"""

[character]
success_symbol = "[❯](white)"

[directory]
style = "yellow"
read_only = "  "

[git_branch]
symbol = " "
style = "green"

[git_status]
format = "([$all_status$ahead_behind]($style) )"
up_to_date = "•"
conflicted = ""
stashed = ""
modified = "⋯"
deleted = ""
style = "white"

[git_commit]
tag_symbol = " "

[lua]
symbol = " "

[nodejs]
style = "purple"

[cmd_duration]
min_time = 0
format = "[$duration]($style)"
style = "bold cyan"
