name: Pull Request

on:
  pull_request:
    branches:
      - master

jobs:
  stylua:
    name: Stylua check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: JohnnyMorganz/stylua-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: 0.16.0
          args: --check .
