name: Stylua

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  stylua:
    name: Stylua
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Stylua
        uses: JohnnyMorganz/stylua-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: 2.0.2
          args: --check .
